import { ErrorDescription, ErrorTitle } from "@/types/global";
import { ErrorPageProps } from "@/types/props";
import { Link } from "@inertiajs/react";

const ErrorPage: React.FC<ErrorPageProps> = ({ status }) => {
    const title: ErrorTitle = {
        100: '100: Continuer',
        101: '101: Changement de protocole',
        200: '200: OK',
        201: '201: Créé',
        202: '202: Accepté',
        203: '203: Informations non autorisées',
        204: '204: Aucun contenu',
        205: '205: Réinitialiser le contenu',
        206: '206: Contenu partiel',
        300: '300: Choix multiples',
        301: '301: Déplacé de manière permanente',
        302: '302: Trouvé',
        303: '303: Voir ailleurs',
        304: '304: Non modifié',
        305: '305: Utiliser un mandataire',
        307: '307: Redirection temporaire',
        400: '400: Requête incorrecte',
        401: '401: Non autorisé',
        402: '402: Paiement requis',
        403: '403: Interdit',
        404: '404: Page non trouvée',
        405: '405: Méthode non autorisée',
        406: '406: Non acceptable',
        407: '407: Authentification de mandataire requise',
        408: '408: Délai d\'attente de la requête',
        409: '409: Conflit',
        410: '410: Perdu de façon permanente',
        411: '411: Longueur requise',
        412: '412: Échec de la précondition',
        413: '413: Entité de demande trop volumineuse',
        414: '414: URI trop long',
        415: '415: Type de support non pris en charge',
        416: '416: Plage de demandes non satisfaisante',
        417: '417: Erreur d\'attente préalable',
        418: '418: Je suis une théière',
        422: '422: Entité non traitable',
        423: '423: Verrouillé',
        424: '424: Échec de la dépendance',
        425: '425: Trop tôt',
        426: '426: Mise à niveau requise',
        428: '428: Condition préalable requise',
        429: '429: Trop de requêtes',
        431: '431: Demande d\'en-tête de champ de l\'en-tête trop volumineuse',
        500: '500: Erreur du serveur',
        501: '501: Non mis en œuvre',
        502: '502: Mauvaise passerelle',
        503: '503: Service non disponible',
        504: '504: Délai d\'attente de la passerelle',
        505: '505: Version HTTP non prise en charge',
        506: '506: Variante également négociable',
        507: '507: Stockage insuffisant',
        508: '508: Boucle détectée',
        510: '510: Extension non étendue',
        511: '511: Authentification réseau requise',
    }[status];

    const description: ErrorDescription = {
        100: 'Continuez simplement avec la requête.',
        101: 'Le serveur est prêt à passer à des protocoles différents.',
        200: 'La requête a réussi.',
        201: 'La requête a été satisfaite et a entraîné la création d\'une nouvelle ressource.',
        202: 'La requête a été acceptée pour traitement, mais le traitement n\'est pas encore terminé.',
        203: 'Les informations ne sont pas autorisées pour cette requête.',
        204: 'Aucun contenu à renvoyer.',
        205: 'Réinitialiser le contenu de la requête.',
        206: 'Le serveur a accompli une partie de la requête GET.',
        300: 'La requête a plus d\'une réponse possible. L\'entité, le cas échéant, est une liste de choix représentant des réponses.',
        301: 'La ressource a été déplacée de manière permanente vers une autre localisation et une redirection est nécessaire.',
        302: 'La ressource a été trouvée, mais elle a été déplacée temporairement vers l\'emplacement indiqué.',
        303: 'La réponse à la requête peut être trouvée ailleurs.',
        304: 'La ressource n\'a pas été modifiée depuis la dernière requête spécifiée.',
        305: 'Le client doit utiliser un mandataire pour accéder à la ressource demandée.',
        307: 'La redirection temporaire a eu lieu. La requête initiale doit toujours être refaite avec cette information de redirection.',
        400: 'La requête ne peut pas être traitée en raison d\'une syntaxe incorrecte.',
        401: 'La demande a échoué en raison d\'une authentification incorrecte.',
        402: 'Le paiement est requis pour l\'accès à cette ressource.',
        403: 'L\'accès à la ressource est interdit.',
        404: 'La ressource demandée ne peut pas être trouvée sur ce serveur.',
        405: 'La méthode spécifiée dans la requête n\'est pas autorisée pour la ressource identifiée.',
        406: 'Aucun contenu acceptable selon les en-têtes de la requête.',
        407: 'L\'authentification de mandataire est nécessaire pour accéder à la ressource demandée.',
        408: 'Le serveur a expiré le délai d\'attente de la requête.',
        409: 'La requête ne peut pas être traitée en raison d\'un conflit dans la demande.',
        410: 'La ressource demandée a été perdue de manière permanente. Un lien dans la réponse doit être utilisé pour rétablir la connexion.',
        411: 'La longueur de la requête est requise par le serveur.',
        412: 'L\'échec de la condition préalable empêche le traitement de la requête.',
        413: 'L\'entité de la demande est trop volumineuse pour être traitée.',
        414: 'L\'URI de la requête est trop long pour être traité.',
        415: 'Le type de support de la requête n\'est pas pris en charge par le serveur.',
        416: 'La plage de demandes spécifiée n\'est pas satisfaisante.',
        417: 'L\'attente préalable a échoué.',
        418: 'Je suis une théière.',
        422: 'L\'entité fournie avec la requête est incompréhensible ou mal formée.',
        423: 'La ressource est verrouillée.',
        424: 'L\'échec de la dépendance signifie que l\'ordre d\'exécution des dépendances a échoué.',
        425: 'Trop tôt pour traiter la requête.',
        426: 'La mise à niveau requise pour accéder à la ressource.',
        428: 'La condition préalable requise pour la requête.',
        429: 'Trop de requêtes ont été envoyées par le client.',
        431: 'Le serveur ne traitera pas la demande car la longueur de l\'en-tête de champ de la demande est trop volumineuse.',
        500: 'Erreur interne du serveur.',
        501: 'La fonctionnalité demandée n\'est pas implémentée sur le serveur.',
        502: 'La passerelle serveur a reçu une réponse invalide.',
        503: 'Le service n\'est pas disponible.',
        504: 'La passerelle serveur n\'a pas pu obtenir une réponse à temps.',
        505: 'La version de HTTP dans la requête n\'est pas prise en charge par le serveur.',
        506: 'La variante également négociable, mais seulement le serveur peut fournir.',
        507: 'Le stockage du serveur est insuffisant pour répondre à la demande.',
        508: 'La boucle détectée dans la requête.',
        510: 'L\'extension demandée du serveur n\'a pas été étendue.',
        511: 'L\'authentification réseau est requise pour accéder à la ressource.',
    }[status];

    return (
        <div className="flex flex-col items-center justify-center h-screen">
            <span className="text-3xl font-bold">{ title }</span>

            <span className="text-xl text-gray-700">{ description }</span>

            <Link className="text-blue-500 hover:text-blue-600 transition text-lg mt-8 tracking-wider" href={route("dashboard")}>Go Dashboard</Link>
        </div>
    );
}

export default ErrorPage;
